[package]
name = "ant-book"
version = "0.1.0"
authors = ["shimo8810 <shimo.8810@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
